#!/bin/bash
source $MARVELL_SDK_PATH/setenv.sh
cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_TOOLCHAIN_FILE=$MARVELL_SDK_PATH/toolchain/steamlink-toolchain.cmake -DCMAKE_INSTALL_PREFIX=$MARVELL_SDK_PATH/rootfs/usr -DCMAKE_PREFIX_PATH=$MARVELL_SDK_PATH/rootfs $@ && cmake --build build --target install
