#!/bin/bash
source /opt/devkitpro/switchvars.sh
cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_TOOLCHAIN_FILE=/switch.toolchain -DCMAKE_INSTALL_PREFIX=$DEVKITPRO/portlibs/switch -GNinja $@ && cmake --build build --target install
