#!/bin/sh
mkdir -p build && cd build && emcmake cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_SYSROOT=$EMSCRIPTEN/system/local -DCMAKE_INSTALL_PREFIX=$EMSCRIPTEN/system/local -DCMAKE_PREFIX_PATH=$EMSCRIPTEN/system/local $@ && ninja install
